import path from 'node:path';
import { archiveDownloadLimit, credential, executionEnvironment, handle, packageBytes, redactOutput, shellCommand, shellQuote, writeBoundedStream } from './protocol.mjs';

function resourceId(req) { return req.payload.handle.resource_ids[0].id; }
function memoryMb(value) { const match = /^([1-9][0-9]*)([mg])$/i.exec(String(value)); if (!match) throw Object.assign(new Error('memory requirement must use m or g units'), { code: 'RESOLUTION_INVALID' }); return Number(match[1]) * (match[2].toLowerCase() === 'g' ? 1024 : 1); }

async function e2bConnect(req) {
  const { Sandbox } = await import('e2b');
  return Sandbox.connect(resourceId(req), { apiKey: credential(req, 'e2b') });
}

export const e2b = {
  async provision(req) {
    const { Sandbox } = await import('e2b');
    const netNone = (req.payload.resolved_plan?.requirements?.network?.mode || req.profile.network_mode) === 'none';
    const opts = { apiKey: credential(req, 'e2b'), timeoutMs: req.profile.sandbox_timeout_ms || 300_000, allowInternetAccess: !netNone, metadata: { 'workcell.run_id': req.run_id, 'workcell.nonce': req.payload.ownership.nonce } };
    const sandbox = await Sandbox.create(req.profile.template || 'base', opts);
    const h = handle('e2b', req, sandbox.sandboxId, { allow_internet_access: !netNone });
    return { handle: h, resource_inventory: [{ kind: 'sandbox', id: sandbox.sandboxId, state: 'running', ownership: h.ownership }], actual_resolution: { allow_internet_access: !netNone } };
  },
  async prepare(req) { const sb = await e2bConnect(req); await sb.files.write('/tmp/workcell-workspace.tar', await packageBytes(req.payload.workspace_package)); await verifyAndExtract(req, async (cmd) => sb.commands.run(cmd)); return { handle: req.payload.handle, workspace_root: '/workspace', observed_package_digest: req.payload.workspace_package.sha256 }; },
  async execute(req) { const sb = await e2bConnect(req); let result; try { result = await sb.commands.run(shellCommand(req.payload.argv), { cwd: req.payload.workdir, envs: executionEnvironment(req), timeoutMs: req.payload.timeout_ms }); } catch (error) { if (Number.isInteger(error?.exitCode)) result = error; else throw error; } return commandData('e2b', req, result.exitCode, result.stdout || '', result.stderr || ''); },
  async collect(req) { const sb = await e2bConnect(req); return collectWithCommand(req, async (cmd) => sb.commands.run(cmd)); },
  async export(req) { const sb = await e2bConnect(req); return exportWithCommand(req, async (cmd) => sb.commands.run(cmd), async (remote, local, limit) => writeBoundedStream(local, await sb.files.read(remote, { format: 'stream' }), limit)); },
  async destroy(req) { const { Sandbox } = await import('e2b'); await Sandbox.kill(resourceId(req), { apiKey: credential(req, 'e2b') }); return destroyed(req); },
  async inventory(req) { const { Sandbox } = await import('e2b'); const pager = Sandbox.list({ apiKey: credential(req, 'e2b'), query: { metadata: { 'workcell.run_id': req.run_id, 'workcell.nonce': req.payload.ownership.nonce } } }); const resources = []; for await (const item of pager) if (ownedMetadata(item.metadata, req.payload.ownership, 'workcell.run_id', 'workcell.nonce')) resources.push({ kind: 'sandbox', id: item.sandboxId, state: item.state || 'unknown', ownership: req.payload.ownership }); return { resources, complete: true }; }
};

async function vercelConnect(req) { const { Sandbox } = await import('@vercel/sandbox'); return Sandbox.get({ name: resourceId(req), resume: true }); }
export const vercel = {
  async provision(req) { const { Sandbox } = await import('@vercel/sandbox'); credential(req, 'vercel-sandbox'); const requirements = req.payload.resolved_plan.requirements || {}; const mode = requirements.network?.mode || 'none'; const networkPolicy = mode === 'none' ? 'deny-all' : mode === 'allowlist' ? { allow: requirements.network.allow || [] } : 'allow-all'; const compute = requirements.compute || {}; const resources = { vcpus: compute.cpus }; const sandbox = await Sandbox.create({ name: `wc-${req.run_id.slice(3, 26)}`, persistent: false, timeout: requirements.execution?.timeout_ms || 300_000, image: req.profile.image, resources, networkPolicy, tags: { 'workcell-run-id': req.run_id, 'workcell-nonce': req.payload.ownership.nonce } }); const h = handle('vercel-sandbox', req, sandbox.name, { network_policy: networkPolicy, resources, observed_memory_mb: sandbox.memory ?? null }); return { handle: h, resource_inventory: [{ kind: 'sandbox', id: sandbox.name, state: 'running', ownership: h.ownership }], actual_resolution: { network_policy: networkPolicy, resources, observed_memory_mb: sandbox.memory ?? null } }; },
  async prepare(req) { const sb = await vercelConnect(req); await sb.writeFiles([{ path: '/tmp/workcell-workspace.tar', content: await packageBytes(req.payload.workspace_package) }]); await verifyAndExtract(req, async (cmd) => vercelCommand(sb, cmd)); return { handle: req.payload.handle, workspace_root: '/workspace', observed_package_digest: req.payload.workspace_package.sha256 }; },
  async execute(req) { const sb = await vercelConnect(req); const result = await sb.runCommand({ cmd: req.payload.argv[0], args: req.payload.argv.slice(1), cwd: req.payload.workdir, env: executionEnvironment(req), timeoutMs: req.payload.timeout_ms }); return commandData('vercel-sandbox', req, result.exitCode, await result.stdout(), await result.stderr()); },
  async collect(req) { const sb = await vercelConnect(req); return collectWithCommand(req, async (cmd) => vercelCommand(sb, cmd)); },
  async export(req) { const sb = await vercelConnect(req); return exportWithCommand(req, async (cmd) => sb.runCommand('sh', ['-lc', cmd]), async (remote, local, limit) => { const stream = await sb.readFile({ path: remote }); if (!stream) throw Object.assign(new Error('provider artifact archive was not found'), { code: 'ARTIFACT_MISSING' }); return writeBoundedStream(local, stream, limit); }); },
  async destroy(req) { const sb = await vercelConnect(req); await sb.stop(); return destroyed(req); },
  async inventory(req) { const { Sandbox } = await import('@vercel/sandbox'); credential(req, 'vercel-sandbox'); const pager = await Sandbox.list({ tags: { 'workcell-run-id': req.run_id } }); const resources = []; for await (const item of pager) if (ownedMetadata(item.tags, req.payload.ownership, 'workcell-run-id', 'workcell-nonce')) resources.push({ kind: 'sandbox', id: item.name, state: item.status, ownership: req.payload.ownership }); return { resources, complete: true }; }
};

function daytonaClient(req) { return import('@daytona/sdk').then(({ Daytona }) => new Daytona({ apiKey: credential(req, 'daytona'), apiUrl: req.profile.endpoint || undefined, target: req.profile.region || undefined, otelEnabled: false })); }
async function daytonaConnect(req) { const client = await daytonaClient(req); return { client, sandbox: await client.get(resourceId(req)) }; }
export const daytona = {
  async provision(req) { const client = await daytonaClient(req); const requirements = req.payload.resolved_plan.requirements || {}; const mode = requirements.network?.mode || 'none'; const compute = requirements.compute || {}; const resources = { cpu: compute.cpus, memory: Math.max(1, Math.ceil(memoryMb(compute.memory) / 1024)) }; const params = { name: `wc-${req.run_id.slice(3, 26)}`, image: req.payload.resolved_plan.workload?.image?.reference || 'debian:12.9', resources, ephemeral: true, autoDeleteInterval: 0, ttlMinutes: Math.max(1, Math.ceil((requirements.execution?.timeout_ms || 300_000) / 60_000)), labels: { 'workcell.run_id': req.run_id, 'workcell.nonce': req.payload.ownership.nonce }, networkBlockAll: mode === 'none', domainAllowList: mode === 'allowlist' ? (requirements.network.allow || []).join(',') : undefined }; const sandbox = await client.create(params, { timeout: 120 }); const h = handle('daytona', req, sandbox.id, { sandbox_class: sandbox.class || null, network_mode: mode, resources }); return { handle: h, resource_inventory: [{ kind: 'sandbox', id: sandbox.id, state: sandbox.state || 'started', ownership: h.ownership }], actual_resolution: { sandbox_class: sandbox.class || null, network_mode: mode, resources } }; },
  async prepare(req) { const { sandbox } = await daytonaConnect(req); await sandbox.fs.uploadFile(req.payload.workspace_package.archive_path, '/tmp/workcell-workspace.tar'); await verifyAndExtract(req, async (cmd) => daytonaCommand(sandbox, cmd)); return { handle: req.payload.handle, workspace_root: '/workspace', observed_package_digest: req.payload.workspace_package.sha256 }; },
  async execute(req) { const { sandbox } = await daytonaConnect(req); const result = await sandbox.process.executeCommand(shellCommand(req.payload.argv), req.payload.workdir, executionEnvironment(req), Math.ceil(req.payload.timeout_ms / 1000)); return commandData('daytona', req, result.exitCode, result.result || '', ''); },
  async collect(req) { const { sandbox } = await daytonaConnect(req); return collectWithCommand(req, async (cmd) => daytonaCommand(sandbox, cmd)); },
  async export(req) { const { sandbox } = await daytonaConnect(req); return exportWithCommand(req, async (cmd) => sandbox.process.executeCommand(cmd, '/workspace'), async (remote, local, limit) => writeBoundedStream(local, await sandbox.fs.downloadFileStream(remote), limit)); },
  async destroy(req) { const { sandbox } = await daytonaConnect(req); await sandbox.delete(60, true); return destroyed(req); },
  async inventory(req) { const client = await daytonaClient(req); const resources = []; for await (const item of client.list({ labels: { 'workcell.run_id': req.run_id, 'workcell.nonce': req.payload.ownership.nonce } })) if (ownedMetadata(item.labels, req.payload.ownership, 'workcell.run_id', 'workcell.nonce')) resources.push({ kind: 'sandbox', id: item.id, state: item.state || 'unknown', ownership: req.payload.ownership }); return { resources, complete: true }; }
};

function commandData(provider, req, exitCode, stdout, stderr) { const safeStdout = redactOutput(req, stdout, provider); const safeStderr = redactOutput(req, stderr, provider); const bounded = boundLogs(safeStdout, safeStderr, req.payload.max_output_bytes); return { events: [bounded.stdout ? { stream: 'stdout', bytes: bounded.stdout } : null, bounded.stderr ? { stream: 'stderr', bytes: bounded.stderr } : null].filter(Boolean), data: { handle: req.payload.handle, command_id: `${req.run_id}-command`, terminal: { status: 'exited', exit_code: exitCode, signal: null, reason: 'provider-exit', timed_out: false, cancelled: false, certainty: 'terminal' }, logs: { stdout_bytes: Buffer.byteLength(bounded.stdout), stderr_bytes: Buffer.byteLength(bounded.stderr), truncated: bounded.truncated, complete: !bounded.truncated, ordering: 'per-stream' } } }; }
export function boundLogs(stdout, stderr, maximum) { const limit = Number.isSafeInteger(maximum) && maximum > 0 ? maximum : 4_000_000; const out = Buffer.from(String(stdout)); const first = out.subarray(0, limit); const remaining = Math.max(0, limit - first.length); const err = Buffer.from(String(stderr)); const second = err.subarray(0, remaining); return { stdout: first.toString('utf8'), stderr: second.toString('utf8'), truncated: out.length + err.length > limit }; }
export function ownedMetadata(metadata, ownership, runKey, nonceKey) { return Boolean(metadata && metadata[runKey] === ownership.run_id && metadata[nonceKey] === ownership.nonce); }
async function vercelCommand(sandbox, command) { const result = await sandbox.runCommand('sh', ['-lc', command]); return { exitCode: result.exitCode, stdout: await result.stdout(), stderr: await result.stderr() }; }
async function daytonaCommand(sandbox, command) { const result = await sandbox.process.executeCommand(command, '/workspace'); return { exitCode: result.exitCode, stdout: result.result || '', stderr: '' }; }
function commandStdout(result) { return String(result?.stdout ?? result?.result ?? ''); }
async function verifyAndExtract(req, run) { const expected = req.payload.workspace_package.sha256; const result = await run("sha256sum /tmp/workcell-workspace.tar | awk '{print $1}'"); if (result?.exitCode !== undefined && result.exitCode !== 0) throw Object.assign(new Error('remote workspace digest command failed'), { code: 'WORKSPACE_INTEGRITY' }); if (commandStdout(result).trim() !== expected) throw Object.assign(new Error('remote workspace package digest mismatched'), { code: 'WORKSPACE_INTEGRITY' }); const extracted = await run('mkdir -p /workspace && tar -xf /tmp/workcell-workspace.tar -C /workspace --strip-components=1'); if (extracted?.exitCode !== undefined && extracted.exitCode !== 0) throw Object.assign(new Error('remote workspace extraction failed'), { code: 'WORKSPACE_PREPARE' }); }
export function parseWorkspaceStatus(output) { const entries = String(output).split('\0').filter(Boolean); const files = []; for (let i = 0; i < entries.length; i += 1) { const entry = entries[i]; if (entry.length < 4 || entry[2] !== ' ') throw Object.assign(new Error('workspace delta response was malformed'), { code: 'WORKSPACE_COLLECT' }); const status = entry.slice(0, 2); files.push(entry.slice(3)); if (status.includes('R') || status.includes('C')) { i += 1; if (i >= entries.length) throw Object.assign(new Error('workspace rename response was incomplete'), { code: 'WORKSPACE_COLLECT' }); files.push(entries[i]); } } return [...new Set(files)].sort(); }
async function collectWithCommand(req, run) { const result = await run("git -C /workspace status --porcelain=v1 -z --untracked-files=all"); if (result?.exitCode !== undefined && result.exitCode !== 0) throw Object.assign(new Error('workspace delta collection failed'), { code: 'WORKSPACE_COLLECT' }); const files = parseWorkspaceStatus(commandStdout(result)); return { terminal: { status: 'unknown', exit_code: null, signal: null, reason: 'execute-result-authoritative', timed_out: false, cancelled: false, certainty: 'unknown' }, logs: { complete: true, ordering: 'per-stream' }, workspace_delta: { files, complete: true }, metrics: {}, attempt_inventory: [] }; }
function destroyed(req) { return { items: req.payload.handle.resource_ids.map((r) => ({ ...r, status: 'removed' })), remaining: [] }; }
async function exportWithCommand(req, run, download) { const declared = req.payload.declarations || []; if (declared.length === 0) return { archive: null, manifest: { declared, files: [] }, failures: [], cleanup_resources: [] }; for (const item of declared) if (!/^[A-Za-z0-9._/-]+$/.test(item) || item.includes('..') || item.startsWith('/')) throw Object.assign(new Error('artifact declaration is unsafe'), { code: 'PATH_UNSAFE' }); const remote = `/tmp/workcell-artifacts-${req.run_id}.tar`; await run(`umask 077 && tar -cf ${shellQuote(remote)} -C /workspace -- ${declared.map(shellQuote).join(' ')} && chmod 400 ${shellQuote(remote)}`); const local = path.join(req.payload.destination, 'artifacts.tar'); const archive = await download(remote, local, archiveDownloadLimit(req.payload.limits)); return { archive, manifest: { declared, files: [] }, failures: [], cleanup_resources: [{ kind: 'remote-file', id: remote }] }; }
